### PR TITLE
Added ACE3 updates for DF. Changed default buttons to action buttons 1 & 2

### PR DESCRIPTION
**Pull request by Lagmann**
Added ACE3 updates for DF. Changed default buttons to action buttons 1 and 2 and added them to the suggested commands as well.

### CODE REVIEW

**Comment by meribold** [comment]
Thanks, @Lagmann! But since I pushed a commit that also updates Ace3 minutes before you opened this PR, I'll close it.

**Comment by Lagmann** [comment]
@meribold awesome! Glad you're back! I thought this would be abandoned and I attempted to fix it on my own. Thank you!

**Comment by Lagmann** [comment]
@meribold would you consider adding actionbutton1 and actionbutton2 as the default instead of strafing or at least adding them to the suggested commands?

I already did it in my version but I see other users were asking about it.

**Comment by meribold** [comment]
I don't want to change the defaults, but adding `ACTIONBUTTON1` and `ACTIONBUTTON2` to the suggested command should be fine.

**Pull request closed without merging**
